services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: app/Dockerfile.api
    environment:
      REDIS_ADDR: redis:6379
    ports:
      - "8080:8080"
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: app/Dockerfile.worker
    environment:
      REDIS_ADDR: redis:6379
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:v2.55.1
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - api
      - worker

  grafana:
    image: grafana/grafana:11.3.1
    ports:
      - "3000:3000"
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
