FROM golang:1.25-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY app ./app
RUN go build -o /out/worker ./app/cmd/worker

FROM alpine:3.22
WORKDIR /app
COPY --from=build /out/worker /app/worker
EXPOSE 9091
CMD ["/app/worker"]
